name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download and install Caddy
      run: |
        wget --output-document caddy.deb --quiet https://github.com/caddyserver/caddy/releases/download/v2.7.6/caddy_2.7.6_linux_amd64.deb
        sudo dpkg -i caddy.deb
    - name: Set up Node.js
      uses: actions/setup-node@v7
      with:
        node-version: 24
    - name: Set up just
      uses: extractions/setup-just@v2
    - name: Run tests
      run: just test
