name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Download and install Caddy
      run: wget --quiet https://github.com/caddyserver/caddy/releases/download/v2.4.3/caddy_2.4.3_linux_amd64.deb && sudo dpkg -i caddy_2.4.3_linux_amd64.deb
    - name: Download and install Deno
      run: wget --output-document deno.zip --quiet https://github.com/denoland/deno/releases/download/v1.11.3/deno-x86_64-unknown-linux-gnu.zip && unzip deno.zip deno && sudo install deno /usr/local/bin/
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run tests
      run: make test
